import asyncio
from typing import List, Dict, Any, Type
from pydantic import BaseModel, Field

from core.llm import LLMService 
from skills.base import BaseSkill
from core.state import AgentState

class ResearchInput(BaseModel):
    topic: str = Field(description="The topic to research deeply")

class ResearchSubAgent(BaseSkill):
    """
    Sub-agent that performs deep analysis without polluting the main agent context.
    Orchestrator-Worker pattern implementation.
    """
    name: str = "deep_research_agent"
    description: str = "Performs deep multi-step research on a topic using a separate LLM context."

    def __init__(self, llm_config: Dict[str, Any]):
        # Sub-agent gets its own LLM client instance
        # Map config manually since LLMService takes args, not dict in __init__
        self.llm = LLMService(
            base_url=llm_config.get("base_url"),
            api_key=llm_config.get("api_key"),
            model=llm_config.get("model")
        )

    @property
    def input_schema(self) -> Type[BaseModel]:
        return ResearchInput

    async def execute(self, params: ResearchInput, state: AgentState) -> str:
        query = params.topic
        print(f"[{self.name}] 🧠 Starting Deep Research on: {query}")
        
        # 1. Planning Phase
        plan_prompt = f"Create a 3-step search plan to investigate: {query}. Return ONLY the 3 steps as a list."
        plan = await self.llm.complete(plan_prompt, system_prompt="You are a planning assistant.")
        print(f"[{self.name}] 📋 Plan:\n{plan}")
        
        # 2. Execution Phase (Simulation of browsing)
        # In a real implementation, this would call a SearchTool directly
        print(f"[{self.name}] 🔍 Executing search steps...")
        await asyncio.sleep(2) # Simulate work
        
        # 3. Synthesis Phase
        report_prompt = f"""
        Topic: {query}
        Research Plan Executed: {plan}
        
        Write a concise summary report (max 2 paragraphs) synthesising the findings.
        Assume positive trends for simulation purposes unless specified.
        """
        
        report = await self.llm.complete(report_prompt, system_prompt="You are a Research Analyst.")
        
        return f"### 🧠 Deep Research Report\n\n{report}\n\n*(Generated by Sub-Agent)*"
